config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [ :show ]
  resources :animals, only: [ :index, :show, :new, :create, :destroy ] do
    resources :locations, only: [ :new, :create ]
  end

  resources :locations, only: [ :show ] do
    resources :reviews, only: [ :new, :create ]
  end

  resources :locations do
    member do
      patch "/accept", to: "locations#accept"
      patch "/decline", to: "locations#decline"
    end
  end
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :locations, dependent: :destroy
  has_many :reviews, through: :locations
  validates :name, presence: true
  validates :species, presence: true
  validates :price_per_hour, presence: true
  has_one_attached :photo

  def average_rating
    reviews = self.reviews

    return 0 if reviews.empty?

    reviews.map(&:rating).sum / reviews.length.to_f
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :animal
  belongs_to :user
  has_one :review
  validates :start_date, presence: true
  validates :end_date, presence: true

  scope :pending, -> { where( status: "pending")}
  

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :location
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates_inclusion_of :rating, in: 0..5
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :animals, dependent: :destroy
  has_many :locations

  has_many :requested_bookings, through: :animals, source: :locations

  # has_many :rented_animals, through: :locations, source: :animal
  # has_many :animals_required, through: :animals, source: :locations
  

  has_one_attached :photo
  has_one_attached :banner_photo



end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR species ILIKE :query"
      @animals = Animal.where(sql_query, query: "%#{params[:query]}%")
    else
      @animals = Animal.all
      @top_animals = Animal.all.sort_by { |animal| - animal.average_rating }.first(5)
    end
  end

  def show
    @animal = Animal.find(params[:id])
    @location = Location.new
    @location.animal = @animal
    @reviews = @animal.reviews
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    if @animal.save
      redirect_to animal_path(@animal), notice: "Congrats ! You add A New Best Friend"
    else
      render :new
    end
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :species, :price_per_hour, :photo, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @animals = current_user.animals
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

    def new
        @animal = Animal.find(params[:animal_id])
        @location = Location.new
    end

    def create
        @location = Location.new(location_params)
        @user = current_user
        @animal = Animal.find(params[:animal_id])
        @location.animal = @animal
        @location.user = @user
        redirect_to dashboard_path if @location.save
      end

      def show
        @location = Location.find(params[:id])
      end

      def accept
        @location = Location.find(params[:id])
        # @location.update(status: "Accepted")
        @location.status = "Accepted"
        redirect_to dashboard_path if @location.save
      end

      def decline
        @location = Location.find(params[:id])
        # @location.update(status: "Declined")
        @location.status = "Declined"
        redirect_to dashboard_path if @location.save
      end

      private
    
      def location_params
        params.require(:location).permit(:start_date, :end_date)
      end
   
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @disable_nav = true
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @location = Location.find(params[:location_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @location = Location.find(params[:location_id])
    @review.location = @location
    if @review.save
      redirect_to animal_path(@location.animal)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.erb
<div class="form m-5">
  <%= form_tag animals_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a specific animal or a specific species"
    %>
    <%= button_tag do %>
      <%= icon 'fas', 'search' %>
    <% end %>
  <% end %>
</div>

<% if @top_animals %>
  <h2>Most popular</h2>
  <div class="container-top5">
    <% @top_animals.each do |animal| %>
    <%= link_to animal_path(animal) do %>
    <% if animal.photo.attached? %>
      <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
    <% else %>
        <div class="card-animal">
    <% end %>
        <p class="h2 name"><%= animal.name %></p>
        <p class="h2 species"><%= animal.species %></p>
        <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
      </div>
      <% end %>
    <% end %>
  </div>
<% end %>
<h2>All friends</h2>
<div class="container-cards-animals">
  <% @animals.each do |animal| %>
  <%= link_to animal_path(animal) do %>
  <% if animal.photo.attached? %>
    <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
  <% else %>
      <div class="card-animal">
  <% end %>
      <p class="h2 name"><%= animal.name %></p>
      <p class="h2 species"><%= animal.species %></p>
      <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
    </div>
    <% end %>
  <% end %>
</div>

<footer class="footer">
  <p>Made with <%= icon 'fas', 'heart' %> by Helpers' Team</p>
</footer>

app/views/animals/new.html.erb
<h1 id="add-title">Add A Best Friend </h1>
<div class="create-form">
<%= simple_form_for(@animal) do |f| %>
  <%= f.input :name %>
  <%= f.input :species %>
  <%= f.input :race %>
  <%= f.input :description %>
  <%= f.input :price_per_hour %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Add the animal", class: "btn-add" %>
<% end %>
</div>

app/views/animals/show.html.erb
<div id="header">
<div id="back">
  <%= link_to animals_path, class: "btn"  do %>
  <%= icon 'fas', 'long-arrow-alt-left', "Back" %>
  <% end %>
</div>
  <p class="say-hello">Say <strong>Hello </strong> to <span class="animal-name"><%= @animal.name %></span></p>

  <div id="ref">
    <p> <strong><%= @animal.species.capitalize %></strong></p>
    <% if @animal.race == nil %>
      <p> <%= @animal.race %> </p>
    <% else %>
      <p> <%= @animal.race.capitalize %> </p>
    <% end %>
    <p class="price"> <%= @animal.price_per_hour %> €/Day </p>

    <div id="description">
      <% if @animal.description == nil %>
        <p> <%= @animal.description %> </p>
      <% else %>
        <div id="prout">
          <%= @animal.description.capitalize %>
        </div>
      <% end %>
    </div>
  </div>
 <!--  <a href="#range_start" class="btn btn-primary" style="z-index: 10;">Book now!</a> -->
 </div>

<div id="pic">
<% if @animal.photo.attached? %>
  <%= cl_image_tag(@animal.photo.key,
      width: 400, height: 300, crop: :fill) %>
<% end %>
</div>
<%# this is a test %>
<% if @animal.user != current_user %>
  <div class="cal">
      <%= render '/locations/new' %>
      <div class="reviews">
        <h2>Reviews</h2>
        <% if @animal.reviews.empty? %>
          <p> Waiting for his first review ! </p>
        <% else %>
          <% @reviews.first(5).each do |review| %>
          <div class="review">
            <p> <%= review.rating %> /5 </p>
            <p><%= review.content %></p>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <% else %>

    <div class="not-cal">
      <div class="reviews-owner">
        <h2>Reviews</h2>
        <% if @animal.reviews.empty? %>
          <p> Waiting for his first review ! </p>
        <% else %>
          <% @reviews.first(5).each do |review| %>
          <div class="review-owner">
            <p> <%= review.rating %> /5 </p>
            <p><%= review.content %></p>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/dashboards/show.html.erb
<div class="container-dashboard">
    <p class="welcome">Welcome, <strong> <%= current_user.first_name %> </strong></p>
</div>

<div id="pic">
  <% if current_user.photo.attached? %>
    <%= cl_image_tag(current_user.photo.key,
        width: 400, height: 300, crop: :fill) %>
  <% else %>
          <%= image_tag("https://kitt.lewagon.com/placeholder/users/Kobytes",
        width: 400, height: 300, crop: :fill) %>
  <% end %>
</div>

<% if current_user.animals == nil %>
  <div class="add-animal">
    <%= link_to "Add a friend", new_animal_path %>
  </div>
<% else %>

  <div class="container-d">
    <h3>My animals</h3>
    <div class="container-cards-animals">
      <% @animals.each do |animal| %>
      <%= link_to animal_path(animal) do %>
      <% if animal.photo.attached? %>
          <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
        <% else %>
          <div class="card-animal">
        <% end %>
          <p class="h2 name"><%= animal.name %></p>
          <p class="h2 species"><%= animal.species %></p>
          <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
        </div>
        <% end %>
      <% end %>
        <%= link_to new_animal_path, class: "card-animal" do %>
        <div class="add-image">
        
        </div>
          <%= icon 'fas', 'plus-circle', class: "not-blured" %>
        <% end %>
    </div>
  </div>
<% end %>
  
<% if @animals != nil %>

  <h3>Booking requests of my animals</h3>
  <div class="request-cards">
    <% @animals.each do |animal| %>
      <% animal.locations.where(status: "Pending").each do |location| %>
        <% if animal.photo.attached? %>
          <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
        <% else %>
          <div class="card-animal">
        <% end %>
            <p class="h2 name"><%= animal.name %></p>
            <p> By<%= location.user.first_name %></p>
            <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
            <%= link_to "Accept", accept_location_path(location), method: :patch %>
            <%= link_to "Decline", decline_location_path(location), method: :patch %>
        </div>
        <% end %>
    <% end %>
  </div>
  

  <h3>Accepted Bookings</h3>
  <div class="request-cards">
    <% @animals.each do |animal| %>
        <% animal.locations.where(status: "Accepted").each do |location| %>
          <% if animal.photo.attached? %>
          <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
        <% else %>
          <div class="card-animal">
        <% end %>
              <p class="h2 name"><%= animal.name %></p>
              <p> By <%= location.user.first_name %></p>
              <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
              <%= link_to "Decline", decline_location_path(location), method: :patch %>
          </div>
          <% end %>
      <% end %>
  </div>

  <h3>Declined Bookings</h3>
  <div class="request-cards">
    <% @animals.each do |animal| %>
        <% animal.locations.where(status: "Declined").each do |location| %>
          <% if animal.photo.attached? %>
          <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
          <% else %>
          <div class="card-animal">
          <% end %>
              <p class="h2 name"><%= animal.name %></p>
              <p> By <%= location.user.first_name %></p>
              <p class="h2 price"><%= animal.price_per_hour %>€/day</p>
          </div>
          <% end %>
      <% end %>
  </div>

<% end %>
  
<% if current_user.locations != nil %>

  <% if current_user.locations.map(&:status).include? "Pending" %>
    <h3>My pending bookings</h3>
    <div class="my-pending-bookings">
    <% current_user.locations.each do |location| %>
      <% if location.status == "Pending" %>
            <div class="card-location">
              <p><strong><%= location.animal.name %></strong></p>
              <p><%= location.start_date.strftime("%A - %d - %B") %></p>
              <p><%= location.end_date.strftime("%A - %d - %B") %></p>
              <p><%= location.status %></p>
            </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
    
  <% if current_user.locations.map(&:status).include? "Accepted" %>
    <h3>My Accepted bookings</h3>
    <% current_user.locations.each do |location| %>
      <% if location.status == "Accepted" %>
        <div class="my-pending-bookings">
            <div class="card-location">
              <p><strong><%= location.animal.name %></strong></p>
              <p><%= location.start_date.strftime("%A - %d - %B") %></p>
              <p><%= location.end_date.strftime("%A - %d - %B") %></p>
              <p><%= location.status %></p>
              <%= link_to "Leave a review", new_location_review_path(location) %>
            </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
  
  <% if current_user.locations.map(&:status).include? "Declined" %>
    <h3>My Declined bookings</h3>
    <% current_user.locations.each do |location| %>
      <% if location.status == "Declined" %>
        <div class="my-pending-bookings">
            <div class="card-location">
              <p><strong><%= location.animal.name %></strong></p>
              <p><%= location.start_date.strftime("%A - %d - %B") %></p>
              <p><%= location.end_date.strftime("%A - %d - %B") %></p>
              <p><%= location.status %></p>
            </div>
        <% end %>
      <% end %>
    </div>
  <% end %>

<% end %>

      
      

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookYourFriends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' unless @disable_nav %>
    <%= yield %>
  </body>
</html>

app/views/locations/_new.html.erb
<div class="coucou">
  <div class="form-wrapper">
    <h2>Book your Friend</h2>
    <%= simple_form_for [@animal, @location] do |f| %>
      <%= f.input :start_date, as: :hidden, required: false, input_html: { id: "range_start", class: "datepicker d-none"} %>
      <%= f.input :end_date, label: false, as: :hidden, required: false, input_html: { id: "range_end", class: "datepicker" } %>
      <div class="submit-location">
        <%= f.button :submit, "Book #{@animal.name}", class: "btn btn-primary" %>
      </div>
    <% end %>
    </div>
</div>

app/views/pages/home.html.erb
<div class="container-animal">
  <h1>Book Your Friend ®</h1>
  <p class="h2"><ins>Animal lovers ?</ins> Book and rent animals for several days easily and in a few clicks</p>
  <%= link_to 'Get started !', animals_path %>
</div>

app/views/reviews/new.html.erb
<div class="container">
    <h1>How was your experience ?</h1>
    <%= simple_form_for([ @location, @review ]) do |f|%>
        <%= f.input :rating %>
        <%= f.input :content %>
        <%= f.submit "Post my review", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="navbar-brand">
 <%= image_tag("Paw_(Animal_Rights_symbol).svg.png",
        width: 70, height: 50, crop: :fill) %> <%= link_to "Book your Friend", animals_path %>
</div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<%= link_to "Rent your animal", new_animal_path, class: "btn-create" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/Kobytes", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <a href="#" class="text-muted dropdown-item" value="disabled">Messages</a>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/old_index.html.erb
<div class="hero-banner shadow-lg bg-body">
  <h1>Book Your Friend ®</h1>
  <h2>Have fun with an animal for a day ~</h2>
  <p class="h2 text-muted text-center">Owner of an animal? Rent it!</p>
  <%= link_to "C'est parti !", new_animal_path %>
</div>

<div class="container-cards-animals">
  <% @animals.each do |animal| %>
  <%= link_to animal_path(animal) do %>
    <div class="card-animal" style="background-image: url('<%= cl_image_path animal.photo.key, height: 300, width: 300, crop: :fill %>')">
      <p class="h2 name"><%= animal.name %></p>
      <p class="h2 species"><%= animal.species %></p>
      <p class="h2 price"><%= animal.price_per_hour %>€/h</p>
    </div>
    <% end %>
  <% end %>
</div>

<footer class="footer">
  <p>Made with <%= icon 'fas', 'heart' %> by Helpers' Team</p>
</footer>